name: Cypress tests

on: [push]
  #pull_request:
    #branches:
      #- main
 # push:
    #branches:
     # - main

jobs:
  test:
    runs-on: ubuntu-latest
    #if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install
      - run: npx cypress run
  #test-production:
    #runs-on: ubuntu-latest
    #if: github.event_name == 'push'
    #steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
       # with:
         # node-version: 12.x
     # - run: npm install
     # - run: npm run cy:run -- --env environment=production
