# Note: make sure to use the same version of cypress-io/github-action
# in all jobs, otherwise the last version wins I believe #Karim H
name: Using Cypress GH Action

on: push

jobs:
  single-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start

  parallel-runs:
    name: Parallel 4x
    runs-on: ubuntu-16.04
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 4 copies of the current job in parallel
        # the actual items in the array do not matter
        # we just need to "force" GitHub CI to create 4 jobs
        machines: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: run tests
        uses: cypress-io/github-action@v1
        timeout-minutes: 5
        with:
          record: true
          parallel: true
          group: GH Action parallel
          start: npm start
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 946359c6-b35e-4883-b24f-702a9cb281e0

 
