name: Chrome headless

on: push

jobs:
  chrome-headless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Headless Chrome
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
        
          start: npm start
          browser: chrome
          headless: true
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 946359c6-b35e-4883-b24f-702a9cb281e0
