# workflow report cypress
name : Generate Cypress Report
on:
  push:
    branches:
      - 'master'
jobs:
  cypress-test:
    
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.14.1-chrome83-ff77
    steps:
      -uses: action/checkout@v2
      -name: Install cypress and verify
      run:
       npm ci
       $(npm bin)/cypress verify
       
    -name: Run Cypress Test
     run:
     npm run test:chrome
         continue-on-error: false
                   
    
   -name: Copy Test Execution Screenshots and Videos
    run: 
     mkdir public
    cp -r cypress/videos public/videos
    cp -r cypress/screenshots public/screenshots
    
     -name: Merge test report
     run: npm run combine:report
     
      -name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
     
     -name: generate HTML REPORT
      run npm run generate:report
