name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run --record --key 946359c6-b35e-4883-b24f-702a9cb281e0
        uses: cypress-io/github-action@v1
        with:
          record: true
        
